[irc]
[irc.libera]
Server="irc.libera.chat:6667"
Nick="BeerchatTestBot"
RemoteNickFormat="<{NICK}> "
ShowJoinPart=true

[api.myapi]
BindAddress="0.0.0.0:4242"
Token="mytoken"
Buffer=1000
RemoteNickFormat="{NICK}"
ShowJoinPart=true

[[gateway]]
name="main"
enable=true
[[gateway.inout]]
account="irc.libera"
channel="#beerchat"
[[gateway.inout]]
account="api.myapi"
channel="api"

[[gateway]]
name="main2"
enable=true
[[gateway.inout]]
account="irc.libera"
channel="#beerchat2"
[[gateway.inout]]
account="api.myapi"
channel="api"